package com.project.zeevCode.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.project.zeevCode.dto.SeedResult;
import com.project.zeevCode.entity.Problem;
import com.project.zeevCode.entity.ProblemCollection;
import com.project.zeevCode.entity.ProblemCollectionMembership;
import com.project.zeevCode.entity.TestCase;
import com.project.zeevCode.enums.Difficulty;
import com.project.zeevCode.repository.ProblemCollectionMembershipRepository;
import com.project.zeevCode.repository.ProblemCollectionRepository;
import com.project.zeevCode.repository.ProblemRepository;
import com.project.zeevCode.repository.TestCaseRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Seeds a problem collection from a derived static dataset
 * (judge-frontend/public/data/dsa/&lt;slug&gt;/). The dataset - generated by
 * judge-frontend/scripts/build-neetcode150.mjs - is the single source of truth
 * for list membership, ordering and problem content.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class DatasetSeederService {

    private static final Pattern EXAMPLE_INPUT_OUTPUT =
            Pattern.compile("Input:\\s*([\\s\\S]*?)\\n\\s*Output:\\s*([\\s\\S]*?)(?:\\n\\s*Explanation:|\\z)");

    private final ProblemRepository problemRepository;
    private final TestCaseRepository testCaseRepository;
    private final ProblemCollectionRepository collectionRepository;
    private final ProblemCollectionMembershipRepository membershipRepository;
    private final ObjectMapper objectMapper;

    @Value("${zeevcode.dataset-dir:../judge-frontend/public/data/dsa}")
    private String datasetDir;

    @Transactional
    public SeedResult seedFromDataset(String listSlug, boolean dryRun) {
        int total = 0, created = 0, skipped = 0, failed = 0;
        List<String> details = new ArrayList<>();

        Path manifestPath = Path.of(datasetDir).resolve(listSlug).resolve("manifest.json");
        if (!Files.isRegularFile(manifestPath)) {
            return new SeedResult(dryRun, 0, 0, 0, 1,
                    List.of("FATAL: dataset manifest not found at " + manifestPath.toAbsolutePath()));
        }

        try {
            JsonNode manifest;
            try (InputStream is = Files.newInputStream(manifestPath)) {
                manifest = objectMapper.readTree(is);
            }
            JsonNode problems = manifest.get("problems");
            if (problems == null || !problems.isArray() || problems.isEmpty()) {
                return new SeedResult(dryRun, 0, 0, 0, 1, List.of("FATAL: manifest contains no problems"));
            }
            total = problems.size();
            String listName = manifest.hasNonNull("name") ? manifest.get("name").asText() : listSlug;

            ProblemCollection collection = null;
            if (!dryRun) {
                collection = collectionRepository.findBySlug(listSlug)
                        .orElseGet(() -> collectionRepository.save(
                                ProblemCollection.builder()
                                        .name(listName)
                                        .slug(listSlug)
                                        .description("Seeded from the " + listName + " dataset.")
                                        .build()));
            }

            for (JsonNode item : problems) {
                int order = item.path("order").asInt(0);
                String slug = item.path("slug").asText();
                String title = item.path("title").asText();
                String leetcodeId = item.path("leetcodeId").asText();
                String file = item.path("file").asText(null);
                try {
                    if (slug.isBlank() || title.isBlank() || file == null) {
                        failed++;
                        details.add("FAIL: #" + order + " manifest entry is missing slug/title/file");
                        continue;
                    }

                    JsonNode p;
                    try (InputStream is = Files.newInputStream(manifestPath.getParent().resolve(file))) {
                        p = objectMapper.readTree(is);
                    }

                    String difficultyRaw = item.hasNonNull("difficulty")
                            ? item.get("difficulty").asText()
                            : p.path("difficulty").asText();
                    Difficulty difficulty = mapDifficulty(difficultyRaw);

                    Optional<Problem> existing = problemRepository.findBySlug(slug);
                    if (existing.isPresent()) {
                        Problem problem = existing.get();
                        if (!problem.isSeeded()) {
                            skipped++;
                            details.add("SKIP: " + slug + " already exists and is manually managed");
                            ensureMembership(problem, collection, order, dryRun);
                            continue;
                        }
                        if (!dryRun) {
                            problem.setTitle(title);
                            problem.setDifficulty(difficulty);
                            problem.setDescription(buildDescription(p));
                            problem.setTemplateCode(pickTemplateCode(p));
                            problem.setCategory(firstTopic(p));
                            problem.setSourceUrl("https://leetcode.com/problems/" + slug + "/");
                            problem.setLeetcodeNumber(parseIntOrNull(leetcodeId));
                            Problem saved = problemRepository.save(problem);
                            replaceTestCases(saved, p);
                            ensureMembership(saved, collection, order, dryRun);
                        }
                        details.add("UPDATE: " + slug);
                    } else {
                        created++;
                        if (!dryRun) {
                            Problem problem = Problem.builder()
                                    .title(title)
                                    .slug(slug)
                                    .difficulty(difficulty)
                                    .description(buildDescription(p))
                                    .templateCode(pickTemplateCode(p))
                                    .timeLimit(2000)
                                    .memoryLimit(256)
                                    .isActive(true)
                                    .isSeeded(true)
                                    .category(firstTopic(p))
                                    .sourceUrl("https://leetcode.com/problems/" + slug + "/")
                                    .leetcodeNumber(parseIntOrNull(leetcodeId))
                                    .build();
                            Problem saved = problemRepository.save(problem);
                            createTestCases(saved, p);
                            ensureMembership(saved, collection, order, dryRun);
                        }
                        details.add("CREATE: " + slug);
                    }
                } catch (Exception e) {
                    failed++;
                    details.add("FAIL: #" + order + " " + slug + ": " + e.getMessage());
                }
            }
        } catch (Exception e) {
            log.error("Failed to seed dataset {}", listSlug, e);
            failed++;
            details.add("FATAL: " + e.getMessage());
        }

        return new SeedResult(dryRun, total, created, skipped, failed, details);
    }

    private void ensureMembership(Problem problem, ProblemCollection collection, int order, boolean dryRun) {
        if (dryRun || collection == null) return;
        Optional<ProblemCollectionMembership> existing =
                membershipRepository.findByProblemIdAndCollectionId(problem.getId(), collection.getId());
        if (existing.isPresent()) {
            ProblemCollectionMembership membership = existing.get();
            if (membership.getOrderIndex() == null || membership.getOrderIndex() != order) {
                membership.setOrderIndex(order);
                membershipRepository.save(membership);
            }
            return;
        }
        membershipRepository.save(ProblemCollectionMembership.builder()
                .problem(problem)
                .collection(collection)
                .orderIndex(order)
                .build());
    }

    private void replaceTestCases(Problem problem, JsonNode p) {
        testCaseRepository.deleteByProblemId(problem.getId());
        createTestCases(problem, p);
    }

    private void createTestCases(Problem problem, JsonNode p) {
        JsonNode examples = p.get("examples");
        if (examples == null || !examples.isArray()) return;
        for (JsonNode example : examples) {
            JsonNode textNode = example.get("example_text");
            if (textNode == null) continue;
            Matcher matcher = EXAMPLE_INPUT_OUTPUT.matcher(textNode.asText());
            if (!matcher.find()) continue;
            String input = matcher.group(1).trim();
            String expected = matcher.group(2).trim();
            if (input.isEmpty() || expected.isEmpty()) continue;
            testCaseRepository.save(TestCase.builder()
                    .problem(problem)
                    .hidden(false)
                    .input(input)
                    .expectedOutput(expected)
                    .build());
        }
    }

    private String buildDescription(JsonNode p) {
        StringBuilder sb = new StringBuilder();
        String description = p.path("description").asText(null);
        if (description != null && !description.isBlank()) {
            sb.append(description.trim());
        }
        appendSection(sb, "Constraints", p.get("constraints"), false);
        appendSection(sb, "Hints", p.get("hints"), true);
        appendSection(sb, "Follow-up", p.get("follow_ups"), false);
        return sb.toString();
    }

    private void appendSection(StringBuilder sb, String heading, JsonNode list, boolean numbered) {
        if (list == null || !list.isArray() || list.isEmpty()) return;
        sb.append("\n\n").append(heading).append(':');
        int index = 1;
        for (JsonNode node : list) {
            String line = node.asText().trim();
            if (line.isEmpty()) continue;
            sb.append("\n").append(numbered ? (index++) + ". " : "- ").append(line);
        }
    }

    private String pickTemplateCode(JsonNode p) {
        JsonNode snippets = p.get("code_snippets");
        if (snippets != null && snippets.isObject()) {
            for (String lang : new String[]{"java", "python3", "python"}) {
                JsonNode snippet = snippets.get(lang);
                if (snippet != null && !snippet.asText().isBlank()) return snippet.asText();
            }
            Iterator<String> it = snippets.fieldNames();
            while (it.hasNext()) {
                String lang = it.next();
                if (lang.equals("racket") || lang.equals("erlang") || lang.equals("elixir")) continue;
                JsonNode snippet = snippets.get(lang);
                if (snippet != null && !snippet.asText().isBlank()) return snippet.asText();
            }
        }
        return "class Solution {\n\n}";
    }

    private String firstTopic(JsonNode p) {
        JsonNode topics = p.get("topics");
        if (topics != null && topics.isArray() && topics.size() > 0) {
            String topic = topics.get(0).asText().trim();
            if (!topic.isEmpty()) return topic;
        }
        return null;
    }

    private Integer parseIntOrNull(String value) {
        try {
            return Integer.valueOf(value);
        } catch (NumberFormatException e) {
            return null;
        }
    }

    private Difficulty mapDifficulty(String raw) {
        if (raw == null) return Difficulty.MEDIUM;
        String upper = raw.trim().toUpperCase();
        if (upper.startsWith("E")) return Difficulty.EASY;
        if (upper.startsWith("H")) return Difficulty.HARD;
        return Difficulty.MEDIUM;
    }
}
