FROM eclipse-temurin:21-jre
WORKDIR /app
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*
ENV PORT=8081
EXPOSE 8081
COPY app.jar app.jar
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
